[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "psp-cbdc-ml"
version = "0.1.0"
description = "Prototype PSP + CBDC + ML engine"
authors = [{ name="John George Alexander" }]
dependencies = [
    "fastapi",
    "uvicorn",
    "pytest",
    "requests"
]