name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests with coverage
      env:
        PYTHONPATH: .   # ✅ ensure backend is importable
        ADMIN_KEY: ${{ secrets.ADMIN_KEY }}   # ✅ secure secret
      run: pytest -v tests/ --cov=backend --cov-report=term-missing